/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:75c1287a-b6e8-4864-9d34-9622c391af4f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_tEjckQ5pm",
    "aws_user_pools_web_client_id": "3v0tljdgsbonfepqp4cgs96st7",
    "oauth": {}
};


export default awsmobile;
