/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b678f8ba-0d71-4c5b-93fa-ecf0d035caa6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_wfmyd7ZRn",
    "aws_user_pools_web_client_id": "631d005a24b7e06ul5t2v2jpd4",
    "oauth": {}
};


export default awsmobile;
